const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED"; 
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

const MESSAGE_DELETED = "MESSAGE_DELETED";
const MESSAGE_UPDATED = "MESSAGE_UPDATED";
const MEMBER_REMOVED = "MEMBER_REMOVED";
const MEMBER_REMOVED_ALERT = "MEMBER_REMOVED_ALERT";

const MEMBER_ADDED = "MEMBER_ADDED";
const MEMBER_ADDED_ALERT = "MEMBER_ADDED_ALERT";
const MEMBER_LEFT = "MEMBER_LEFT";
const MEMBER_JOINED = "MEMBER_LEFT";


const TAGGED = "TAGGED";


export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  MESSAGE_DELETED,
  MESSAGE_UPDATED,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  MEMBER_REMOVED,
  MEMBER_REMOVED_ALERT,
  MEMBER_ADDED,
  MEMBER_ADDED_ALERT,
  MEMBER_LEFT,
  MEMBER_JOINED,
  TAGGED
};
